global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: travel-ops-api
    metrics_path: /metrics
    static_configs:
      - targets:
          - travel-ops-api:8000
